site:
  title: CentOS Documentation
  start_page: 8-docs::index
content:
  sources:
   - url: .
     branches: HEAD
ui:
  bundle:
    url: http://file.brq.redhat.com/~pbokoc/ui-bundle.zip
    snapshot: true
  default_layout: default
output:
  clean: true
  dir: ./public
  destinations:
  - provider: archive
runtime:
  pull: true
  cache_dir: ./cache
