[id="hardware_compatibility_{context}"]
= Hardware compatibility

[[sect-installation-planning-hardware-compatibility-ppc]]
=== Is your hardware compatible?

{ProductName}{nbsp}7 (big endian) is compatible with IBM Power{nbsp}Systems servers which use the POWER7, POWER8, and POWER9 processor series. POWER6 processors and older are no longer supported.

{ProductName} also offers a little endian variant for IBM Power{nbsp}Systems. This variant is currently compatible with POWER8 and POWER9 processors, and is supported as a KVM guest on Red{nbsp}Hat Enterprise{nbsp}Virtualization for Power, on PowerVM, and PowerNV (bare metal).

The most recent list of supported hardware can be found in the [citetitle]_Red{nbsp}Hat Hardware Compatibility List_, available online at link:++https://access.redhat.com/ecosystem/search/#/category/Server++[]. Also see link:++https://access.redhat.com/site/articles/rhel-limits++[{ProductName} technology capabilities and limits] for general information about system requirements.
