[id="ibm-installation-tools_{context}"]
= IBM Installation Tools

== IBM Installation Toolkit

link:http://www14.software.ibm.com/webapp/set2/sas/f/lopdiags/installtools/home.html[IBM Installation Toolkit]  is an optional utility that speeds up the installation of Linux on IBM Power{nbsp}Systems and is especially helpful for those unfamiliar with Linux. You can use the link:http://www14.software.ibm.com/webapp/set2/sas/f/lopdiags/installtools/home.html[IBM Installation Toolkit] to:

* Install and configure Linux on a non-virtualized IBM Power{nbsp}Systems server.

* Install and configure Linux on servers with previously-configured logical partitions (LPARs, also known as virtualized servers).

* Install IBM service and productivity tools on a new or previously installed Linux system. The IBM service and productivity tools include dynamic logical partition (DLPAR) utilities.

* Upgrade system firmware level on IBM Power{nbsp}Systems servers.

* Perform diagnostics or maintenance operations on previously installed systems.

* Migrate a LAMP server (software stack) and application data from a System x to a System p system. A LAMP server is a bundle of open source software. LAMP is an acronym for Linux, [application]*Apache HTTP Server*, [application]*MySQL* relational database, and the PHP (or sometimes Perl, or Python) language.
