[id="raid-and-other-disk-devices_{context}"]
= RAID and other disk devices

Some storage technologies require special consideration when using {ProductName}. Generally, it is important to understand how these technologies are configured, visible to {ProductName}, and how support for them might have changed between major versions.

== RAID and Other Disk Devices

* Redundant Array of Independent Disks (RAID) allows a group, or array, of drives to act as a single device.

=== Hardware RAID

* Any RAID functions provided by the mainboard of your computer, or attached controller cards, need to be configured before you begin the installation process. Each active RAID array appears as one drive within {ProductName}.

=== Software RAID

* On systems with more than one hard drive, you can use the {ProductName} installation program to operate several of the drives as a Linux software RAID array. With a software RAID array, RAID functions are controlled by the operating system rather than dedicated hardware.

[NOTE]
====
When a pre-existing RAID array's member devices are all unpartitioned disks/drives, the installer will treat the array itself as a disk and will not provide a way to remove the array.
====

=== USB Disks

* You can connect and configure external USB storage after installation. Most such devices are recognized by the kernel and available for use at that time.

Some USB drives might not be recognized by the installation program. If configuration of these disks at installation time is not vital, disconnect them to avoid potential problems.

[discrete]
== Additional Resources

* For more information on software RAID functions, see
//<<sect-custom-partitioning-ppc>>.
