[id="dynamically-activating-an-fcp-lun_{context}"]
= Dynamically activating an FCP LUN

Follow these steps to activate a LUN:

. Use the [command]`cio_ignore` utility to remove the FCP adapter from the list of ignored devices and make it visible to Linux:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r device_number
....
+
Replace _device_number_ with the device number of the FCP adapter. For example:

. To bring the FCP adapter device online, use the following command:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] chccwdev -e fc00
....

. Verify that the required WWPN was found by the automatic port scanning of the zfcp device driver:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] ls -l /sys/bus/ccw/drivers/zfcp/0.0.fc00/
drwxr-xr-x.  3 root root    0 Apr 28 18:19 0x500507630040710b
drwxr-xr-x.  3 root root    0 Apr 28 18:19 0x50050763050b073d
drwxr-xr-x.  3 root root    0 Apr 28 18:19 0x500507630e060521
drwxr-xr-x.  3 root root    0 Apr 28 18:19 0x500507630e860521
-r--r--r--.  1 root root 4096 Apr 28 18:17 availability
-r--r--r--.  1 root root 4096 Apr 28 18:19 card_version
-rw-r--r--.  1 root root 4096 Apr 28 18:17 cmb_enable
-r--r--r--.  1 root root 4096 Apr 28 18:17 cutype
-r--r--r--.  1 root root 4096 Apr 28 18:17 devtype
lrwxrwxrwx.  1 root root    0 Apr 28 18:17 driver ->  ../../../../bus/ccw/drivers/zfcp
-rw-r--r--.  1 root root 4096 Apr 28 18:17 failed
-r--r--r--.  1 root root 4096 Apr 28 18:19 hardware_version
drwxr-xr-x. 35 root root    0 Apr 28 18:17 host0
-r--r--r--.  1 root root 4096 Apr 28 18:17 in_recovery
-r--r--r--.  1 root root 4096 Apr 28 18:19 lic_version
-r--r--r--.  1 root root 4096 Apr 28 18:17 modalias
-rw-r--r--.  1 root root 4096 Apr 28 18:17 online
-r--r--r--.  1 root root 4096 Apr 28 18:19 peer_d_id
-r--r--r--.  1 root root 4096 Apr 28 18:19 peer_wwnn
-r--r--r--.  1 root root 4096 Apr 28 18:19 peer_wwpn
--w-------.  1 root root 4096 Apr 28 18:19 port_remove
--w-------.  1 root root 4096 Apr 28 18:19 port_rescan
drwxr-xr-x.  2 root root    0 Apr 28 18:19 power
-r--r--r--.  1 root root 4096 Apr 28 18:19 status
lrwxrwxrwx.  1 root root    0 Apr 28 18:17 subsystem ->  ../../../../bus/ccw
-rw-r--r--.  1 root root 4096 Apr 28 18:17 uevent
....

. Activate the FCP LUN by adding it to the port (WWPN) through which you would like to access the LUN:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo 0x4020400100000000 > /sys/bus/ccw/drivers/zfcp/0.0.fc00/0x50050763050b073d/unit_add
....

. Find out the assigned SCSI device name:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] lszfcp -DV
/sys/devices/css0/0.0.0015/0.0.fc00/0x50050763050b073d/0x4020400100000000
/sys/bus/ccw/drivers/zfcp/0.0.fc00/host0/rport-0:0-21/target0:0:21/0:0:21:1089355792
....
