[id="dynamically-setting-dasds-online_{context}"]
= Dynamically setting DASDs online

To set a DASD online, follow these steps:

. Use the [application]`cio_ignore` utility to remove the DASD from the list of ignored devices and make it visible to Linux:
+
[literal,subs="+quotes,verbatim"]
....
# cio_ignore -r device_number
....
+
Replace _device_number_ with the device number of the DASD. For example:
+
[literal,subs="+quotes,verbatim"]
....
# cio_ignore -r 4b2e
....

. Set the device online. Use a command of the following form:
+
[literal,subs="+quotes,verbatim"]
....
# chccwdev -e device_number
....
+
Replace _device_number_ with the device number of the DASD. For example:
+
[literal,subs="+quotes,verbatim"]
....
# chccwdev -e 4b2e
....
+
As an alternative, you can set the device online using sysfs attributes:
+
.. Use the [command]`cd` command to change to the /sys/ directory that represents that volume:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cd /sys/bus/ccw/drivers/dasd-eckd/0.0.4b2e/
pass:quotes[`#`] ls -l
total 0
-r--r--r--  1 root root 4096 Aug 25 17:04 availability
-rw-r--r--  1 root root 4096 Aug 25 17:04 cmb_enable
-r--r--r--  1 root root 4096 Aug 25 17:04 cutype
-rw-r--r--  1 root root 4096 Aug 25 17:04 detach_state
-r--r--r--  1 root root 4096 Aug 25 17:04 devtype
-r--r--r--  1 root root 4096 Aug 25 17:04 discipline
-rw-r--r--  1 root root 4096 Aug 25 17:04 online
-rw-r--r--  1 root root 4096 Aug 25 17:04 readonly
-rw-r--r--  1 root root 4096 Aug 25 17:04 use_diag
....
+
.. Check to see if the device is already online:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cat online
0
....
+
.. If it is not online, enter the following command to bring it online:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo 1 > online
pass:quotes[`#`] cat online
1
....

. Verify which block devnode it is being accessed as:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] ls -l
total 0
-r--r--r--  1 root root 4096 Aug 25 17:04 availability
lrwxrwxrwx  1 root root    0 Aug 25 17:07 block -> ../../../../block/dasdb
-rw-r--r--  1 root root 4096 Aug 25 17:04 cmb_enable
-r--r--r--  1 root root 4096 Aug 25 17:04 cutype
-rw-r--r--  1 root root 4096 Aug 25 17:04 detach_state
-r--r--r--  1 root root 4096 Aug 25 17:04 devtype
-r--r--r--  1 root root 4096 Aug 25 17:04 discipline
-rw-r--r--  1 root root    0 Aug 25 17:04 online
-rw-r--r--  1 root root 4096 Aug 25 17:04 readonly
-rw-r--r--  1 root root 4096 Aug 25 17:04 use_diag
....
+
As shown in this example, device 4B2E is being accessed as /dev/dasdb.

These instructions set a DASD online for the current session, but this is not persistent across reboots. For instructions on how to set a DASD online persistently, see <<persistently-setting-dasds-online_configuring-a-linux-instance-on-ibm-z>>. When you work with DASDs, use the persistent device symbolic links under `/dev/disk/by-path/`.

//The below needs to be updated with the new link since this goes to the beta site.

//See the chapter about persistent storage device naming in the [citetitle]_link:++https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/configuring_and_managing_storage_hardware/assembly_overview-of-persistent-naming-attributes_configuring-and-managing-storage-hardware++[Configuring and Managing Storage Hardware]_ for more in-depth information about different ways to consistently refer to storage devices.
