[id="subscription-manager-post-install-ui_{context}"]
= Registering your system using the Subscription Manager User Interface

This section contains information about how to register your {productname} 8 system using the Subscription Manager User Interface to receive updates and access package repositories.

[discrete]
== Prerequisites

* You have completed the graphical installation as per the recommended workflow described on <<graphical-installation-workflow_graphical-installation>>.
* You have an active, non-evaluation {productname} subscription.
* Your Red Hat subscription status is verified.

[discrete]
== Procedure

. Log in to your system.
//. Click the network connection icon on the system menu on the right side of the top bar to connect to your network.
. From the top left-hand side of the window, click *Activities*.
. From the menu options, click the *Show Applications* icon.
. Click the *Red Hat Subscription Manager* icon, or enter *Red Hat Subscription Manager* in the search.
. Enter your administrator password in the *Authentication Required* dialog box.
+
[NOTE]
====
Authentication is required to perform privileged tasks on the system.
====

. The *Subscriptions* window opens, displaying the current status of Subscriptions, System Purpose, and installed products. Unregistered products display a red X.
. Click the *Register* button.
. The *Register System* dialog box opens. Enter your *Customer Portal* credentials and click the *Register* button.
//. You will be prompt with informations regarding Service Level, Installed Product and Common Service Level for the system Subscription. Choose the Service Level you have subscribed for and click on *Next* button.
//. Confirm the Subscription details and click on *Attach* button.
//. You must receive a message confirmation *Registration with Red Hat Subscription Management is Done!*

The *Register* button in the *Subscriptions* window changes to *Unregister* and installed products display a green X.
You can troubleshoot an unsuccessful registration using the `subscription-manager status` command.

[discrete]
== Additional resources

* For more information about Subscription Manager, see the link:https://access.redhat.com/documentation/en-us/red_hat_subscription_management/1/html-single/rhsm/index/[_Using and Configuring Red Hat Subscription Manager_] document.
