[id="powering-on-your-system-from-a-notebook-or-pc-running-linux_{context}"]
= Powering on your system from a notebook or PC running Linux

To power on your server from a notebook or PC running Linux, follow these steps:

. Open a terminal program.

. To power on your server, run the following command:
+
----
ipmitool -I lanplus -H fsp_ip_address -P _ipmi_password_ power on
----
+
Where _ipaddress_ is the IP address of the Power system and _ipmi_password_ is the password set up for IPMI.

. Immediately activate your IPMI console by running this command:
+
----
ipmitool -I lanplus -H fsp_ip_address -P ipmi_password sol activate
----
+
[TIP]
====
Use your keyboard up arrow to display the previous `ipmitool` command. You can edit previous commands to avoid typing the entire command again.
====

[NOTE]
====
If you need to restart your system, follow these steps:
====

. Deactivate the console by running this command:
+
----
ipmitool -I lanplus -H fsp_ip_address -P ipmi_password sol deactivate
----

. Power your system off with this command:
+
----
 ipmitool -I lanplus -H fsp_ip_address -P ipmi_password power off
----

. Power your system on with this command:
+
----
 ipmitool -I lanplus -H fsp_ip_address -P ipmi_password power on
----

[NOTE]
====
If you have not already done so, insert your DVD into the DVD drive or confirm the installer image in your network
====
