[id="creating-lvm-logical-volume_{context}"]
= Creating an LVM logical volume

Logical Volume Management (LVM) presents a simple logical view of underlying physical storage space, such as hard drives or LUNs. Partitions on physical storage are represented as physical volumes that you can group together into volume groups. You can divide each volume group into multiple logical volumes, each of which is analogous to a standard disk partition. Therefore, LVM logical volumes function as partitions that can span multiple physical disks.

//TODO: Add link the RHEL 8 doc
//For more information, see the link:++https://access.redhat.com/site/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Logical_Volume_Manager_Administration/index.html++[Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 Logical Volume Manager Administration] guide.

[NOTE]
====
LVM configuration is available only in the graphical installation program.
====

[IMPORTANT]
====
During text-mode installation, LVM configuration is not available. To create an LVM configuration, press kbd:[Ctrl + Alt + F2] to use a different virtual console, and run the [command]`lvm` command. To return to the text-mode installation, press kbd:[Ctrl + Alt + F1].
====


.Procedure

. From the left-hand pane of the `Manual Partitioning` window, select the mount point.

. Click the [GUI]`Device Type` drop-down menu and select `LVM`. The `Volume Group` drop-down menu is displayed with the newly-created volume group name.
+
[NOTE]
====

You cannot specify the size of the volume group's physical extents in the configuration dialog. The size is always set to the default value of 4 MiB. If you want to create a volume group with different physical extents, you must create it manually by switching to an interactive shell and using the [command]`vgcreate` command, or use a Kickstart file with the [command]`volgroup --pesize=_size_` command. See the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/performing_an_advanced_rhel_installation/index/[_Performing an advanced RHEL installation_] document for more information about Kickstart.

====


.Additional resources

* For more information about LVM, see the _link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/configuring_and_managing_logical_volumes/index[Configuring and managing logical volumes]_ document.
