[id='configuring-a-root-password_{context}']
= Configuring a root password

You must configure a `root` password to finish the installation process and to log in to the administrator (also known as superuser or root) account that is used for system administration tasks. These tasks include installing and updating software packages and changing system-wide configuration such as network and firewall settings, storage options, and adding or modifying users, groups and file permissions.

[IMPORTANT]
====
* Use one or both of the following ways to gain root privileges to the installed system:
** Use a root account
** Create a user account with administrative privileges (member of the wheel group). The [systemitem]`root` account is always created during the installation. Switch to the administrator account only when you need to perform a task that requires administrator access.
====

[WARNING]
====
The `root` account has complete control over the system. If unauthorized personnel gain access to the account, they can access or delete users' personal files.
====
//TODO: link to security docs about root privileges

.Procedure

. From the *Configuration* window, click *Root Password*. The *Root Password* window opens.

. Type your password in the *Root Password* field.
+
The requirements and recommendations for creating a strong root password are:
+
====
* _Must_ be at least eight characters long
* May contain numbers, letters (upper and lower case) and symbols
* Is case-sensitive
====

. Type the same password in the `Confirm` field.

. Click *Done* to confirm your root password and return to <<beginning-installation_final-installer-configuration>>.
+
[NOTE]
====
If you proceeded with a weak password, you must click *Done* twice.
====
