[id="dasds-that-are-not-part-of-the-root-file-system_{context}"]
= DASDs that are not part of the root file system

DASDs that are not part of the root file system, that is, _data disks_, are persistently configured in the file `/etc/dasd.conf`. It contains one DASD per line. Each line begins with the device bus ID of a DASD. Optionally, each line can continue with options separated by space or tab characters. Options consist of key-value-pairs, where the key and value are separated by an equals sign.

The key corresponds to any valid `sysfs` attribute a DASD can have. The value will be written to the key's `sysfs` attribute. Entries in `/etc/dasd.conf` are activated and configured by udev when a DASD is added to the system. At boot time, all DASDs visible to the system get added and trigger [application]*udev*.

Example content of `/etc/dasd.conf`:

[literal,subs="+quotes,verbatim"]
....
0.0.0207
0.0.0200 use_diag=1 readonly=1
....

Modifications of `/etc/dasd.conf` only become effective after a reboot of the system or after the dynamic addition of a new DASD by changing the system's I/O configuration (that is, the DASD is attached under z/VM). Alternatively, you can trigger the activation of a new entry in `/etc/dasd.conf` for a DASD which was previously not active, by executing the following commands:

. Use the [command]`cio_ignore` utility to remove the DASD from the list of ignored devices and make it visible to Linux:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r device_number
....
+
For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r 021a
....

. Trigger the activation by writing to the `uevent` attribute of the device:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo add > /sys/bus/ccw/devices/device-bus-ID/uevent
....
+
For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo add > /sys/bus/ccw/devices/0.0.021a/uevent
....
