[id="installation-network-parameters-on-ibm-z_{context}"]
= Installation network parameters on IBM Z

These parameters can be used to automatically set up the preliminary network, and can be defined in the CMS configuration file. These parameters are the only parameters that can also be used in a CMS configuration file. All other parameters in other sections must be specified in the parameter file.

`NETTYPE="_type_"`::
+
Where _type_ must be one of the following: `qeth`, `lcs`, or `ctc`. The default is `qeth`.
+
Choose `lcs` for:
+
** OSA-2 Ethernet/Token Ring
+
** OSA-Express Fast Ethernet in non-QDIO mode
+
** OSA-Express High Speed Token Ring in non-QDIO mode
+
** Gigabit Ethernet in non-QDIO mode
+
Choose `qeth` for:
+
** OSA-Express Fast Ethernet
+
** Gigabit Ethernet (including 1000Base-T)
+
** High Speed Token Ring
+
** HiperSockets
+
** ATM (running Ethernet LAN emulation)

`SUBCHANNELS="_device_bus_IDs_"`::
+
Where _device_bus_IDs_ is a comma-separated list of two or three device bus IDs. The IDs must be specified in lowercase.
+
Provides required device bus IDs for the various network interfaces:
+
[literal,subs="+quotes,verbatim,macros"]
....
qeth: SUBCHANNELS="pass:quotes[_read_device_bus_id_],pass:quotes[_write_device_bus_id_],pass:quotes[_data_device_bus_id_]"
lcs or ctc: SUBCHANNELS="pass:quotes[_read_device_bus_id_],pass:quotes[_write_device_bus_id_]"
....
+
For example (a sample qeth SUBCHANNEL statement):
+
[literal,subs="+quotes,verbatim"]
....
SUBCHANNELS="0.0.f5f0,0.0.f5f1,0.0.f5f2"
....

`PORTNAME="_osa_portname_"` `PORTNAME="_lcs_portnumber_"`::
+
This variable supports OSA devices operating in qdio mode or in non-qdio mode.
+
When using qdio mode (`NETTYPE="qeth"`), _osa_portname_ is the portname specified on the OSA device when operating in qeth mode.
+
When using non-qdio mode (`NETTYPE="lcs"`), _lcs_portnumber_ is used to pass the relative port number as a decimal integer in the range of 0 through 15.

`PORTNO="_portnumber_"`::
+
You can add either `PORTNO="0"` (to use port 0) or `PORTNO="1"` (to use port 1 of OSA features with two ports per CHPID) to the CMS configuration file to avoid being prompted for the mode.

`LAYER2="_value_"`::
+
Where _value_ can be `0` or `1`.
+
Use `LAYER2="0"` to operate an OSA or HiperSockets device in layer 3 mode (`NETTYPE="qeth"`). Use `LAYER2="1"` for layer 2 mode. For virtual network devices under z/VM this setting must match the definition of the GuestLAN or VSWITCH to which the device is coupled.
+
To use network services that operate on layer 2 (the Data Link Layer or its MAC sublayer) such as DHCP, layer 2 mode is a good choice.
+
The qeth device driver default for OSA devices is now layer 2 mode. To continue using the previous default of layer 3 mode, set `LAYER2="0"` explicitly.

`VSWITCH="_value_"`::
+
Where _value_ can be `0` or `1`.
+
Specify `VSWITCH="1"` when connecting to a z/VM VSWITCH or GuestLAN, or `VSWITCH="0"` (or nothing at all) when using directly attached real OSA or directly attached real HiperSockets.

`MACADDR="_MAC_address_"`::
+
If you specify `LAYER2="1"` and `VSWITCH="0"`, you can optionally use this parameter to specify a MAC address. Linux requires six colon-separated octets as pairs lower case hex digits - for example, `MACADDR=62:a3:18:e7:bc:5f`. Note that this is different from the notation used by z/VM.
+
If you specify `LAYER2="1"` and `VSWITCH="1"`, you must not specify the `MACADDR`, because z/VM assigns a unique MAC address to virtual network devices in layer 2 mode.

`CTCPROT="_value_"`::
+
Where _value_ can be `0`, `1`, or `3`.
+
Specifies the CTC protocol for `NETTYPE="ctc"`. The default is `0`.

`HOSTNAME="_string_"`::
+
Where _string_ is the host name of the newly-installed Linux instance.

`IPADDR="_IP_"`::
+
Where _IP_ is the IP address of the new Linux instance.

`NETMASK="_netmask_"`::
+
Where _netmask_ is the netmask.
+
The netmask supports the syntax of a prefix integer (from 1 to 32) as specified in IPv4 _classless interdomain routing_ (CIDR). For example, you can specify `24` instead of `255.255.255.0`, or `20` instead of `255.255.240.0`.

`GATEWAY="_gw_"`::
+
Where _gw_ is the gateway IP address for this network device.

`MTU="_mtu_"`::
+
Where _mtu_ is the _Maximum Transmission Unit_ (MTU) for this network device.

`DNS="_server1:server2:additional_server_terms:serverN_"`::
+
Where "_server1:server2:additional_server_terms:serverN_" is a list of DNS servers, separated by colons. For example:
+
[literal,subs="+quotes,verbatim"]
....
DNS="10.1.2.3:10.3.2.1"
....

`SEARCHDNS="_domain1:domain2:additional_dns_terms:domainN_"`::
+
Where "_domain1:domain2:additional_dns_terms:domainN_" is a list of the search domains, separated by colons. For example:
+
[literal,subs="+quotes,verbatim"]
....
SEARCHDNS="subdomain.domain:domain"
....
+
You only need to specify `SEARCHDNS=` if you specify the `DNS=` parameter.
+
`DASD=`::
+
Defines the DASD or range of DASDs to configure for the installation.
+
The installation program supports a comma-separated list of device bus IDs, or ranges of device bus IDs with the optional attributes [option]`ro`, [option]`diag`, [option]`erplog`, and [option]`failfast`. Optionally, you can abbreviate device bus IDs to device numbers with leading zeros stripped. Any optional attributes should be separated by colons and enclosed in parentheses. Optional attributes follow a device bus ID or a range of device bus IDs.
+
The only supported global option is [option]`autodetect`. This does not support the specification of non-existent DASDs to reserve kernel device names for later addition of DASDs. Use persistent DASD device names (for example `/dev/disk/by-path/...`) to enable transparent addition of disks later. Other global options such as [option]`probeonly`, [option]`nopav`, or [option]`nofcx` are not supported by the installation program.
+
Only specify those DASDs that need to be installed on your system. All unformatted DASDs specified here must be formatted after a confirmation later on in the installation program.
+
Add any data DASDs that are not needed for the root file system or the `/boot` partition after installation.
+
For example:
+
[literal,subs="+quotes,verbatim"]
....
DASD="eb1c,0.0.a000-0.0.a003,eb10-eb14(diag),0.0.ab1c(ro:diag)"
....
+
For FCP-only environments, remove the [option]`DASD=` option from the CMS configuration file to indicate no DASD is present.
+
[literal,subs="+quotes,macros,verbatim"]
....
FCP_pass:q[_n_]="_device_bus_ID_ _WWPN_ _FCP_LUN_"
....
+
Where:
+
** _n_ is typically an integer value (for example `FCP_1` or `FCP_2`) but could be any string with alphabetic or numeric characters or underscores.
+
** _device_bus_ID_ specifies the device bus ID of the FCP device representing the _host bus adapter_ (HBA) (for example `0.0.fc00` for device fc00).
+
** _WWPN_ is the world wide port name used for routing (often in conjunction with multipathing) and is as a 16-digit hex value (for example `0x50050763050b073d`).
+
** _FCP_LUN_ refers to the storage logical unit identifier and is specified as a 16-digit hexadecimal value padded with zeroes to the right (for example `0x4020400100000000`).
+
These variables can be used on systems with FCP devices to activate FCP LUNs such as SCSI disks. Additional FCP LUNs can be activated during the installation interactively or by means of a Kickstart file. An example value looks similar to the following:
+
[literal,subs="+quotes,verbatim"]
....
FCP_1="0.0.fc00 0x50050763050b073d 0x4020400100000000"
....
+
[IMPORTANT]
====

Each of the values used in the FCP parameters (for example `FCP_1` or `FCP_2`) are site-specific and are normally supplied by the FCP storage administrator.

====

The installation program prompts you for any required parameters not specified in the parameter or configuration file except for FCP_n.
