[id="ibm-zvm-configuration-file_{context}"]
= IBM Z/VM configuration file

Under z/VM, you can use a configuration file on a CMS-formatted disk. The purpose of the CMS configuration file is to save space in the parameter file by moving the parameters that configure the initial network setup, the DASD, and the FCP specification out of the parameter file.

Each line of the CMS configuration file contains a single variable and its associated value, in the following shell-style syntax: `_variable_=_value_`.

You must also add the `CMSDASD` and `CMSCONFFILE` parameters to the parameter file. These parameters point the installation program to the configuration file:

`CMSDASD=_cmsdasd_address_`::
+
Where _cmsdasd_address_ is the device number of a CMS-formatted disk that contains the configuration file. This is usually the CMS user's `A` disk.
+
For example: `CMSDASD=191`

`CMSCONFFILE=_configuration_file_`::
+
Where _configuration_file_ is the name of the configuration file. *This value must be specified in lower case.* It is specified in a Linux file name format: `_CMS_file_name_._CMS_file_type_`.
+
The CMS file `REDHAT CONF` is specified as `redhat.conf`. The CMS file name and the file type can each be from one to eight characters that follow the CMS conventions.
+
For example: `CMSCONFFILE=redhat.conf`
