[id="miscellaneous-parameters-on-ibm-z_{context}"]
= Miscellaneous parameters on IBM Z

The following parameters can be defined in a parameter file but do not work in a CMS configuration file.

`rd.live.check`::
+
Turns on testing of an ISO-based installation source; for example, when booted from an FCP-attached DVD or using `inst.repo=` with an ISO on local hard disk or mounted with NFS.

`nompath`::
+
Disables support for multipath devices.

`proxy=[_protocol_://][_username_[:__password__]@]_host_[:__port__]`::
+
Specify a proxy to use with installation over HTTP, HTTPS or FTP.

`inst.rescue`::
+
Boot into a rescue system running from a RAM disk that can be used to fix and restore an installed system.

`inst.stage2=_URL_`::
+
Specifies a path to a tree containing `install.img`, not to the `install.img` directly. Otherwise, follows the same syntax as `inst.repo=`. If `inst.stage2` is specified, it typically takes precedence over other methods of finding `install.img`. However, if [application]*Anaconda* finds `install.img` on local media, the `inst.stage2` URL will be ignored.
+
If `inst.stage2` is not specified and `install.img` cannot be found locally, [application]*Anaconda* looks to the location given by `inst.repo=` or `method=`.
+
If only `inst.stage2=` is given without `inst.repo=` or `method=`, [application]*Anaconda* uses whatever repos the installed system would have enabled by default for installation.
+
Use the option multiple times to specify multiple HTTP, HTTPS or FTP sources. The HTTP, HTTPS or FTP paths are then tried sequentially until one succeeds:
+
[literal,subs="+quotes,verbatim"]
....
inst.stage2=http://hostname/path_to_install_tree/
inst.stage2=http://hostname/path_to_install_tree/
inst.stage2=http://hostname/path_to_install_tree/
....

`inst.syslog=_IP/hostname_[:__port__]`::
+
Sends log messages to a remote syslog server.

The boot parameters described here are the most useful for installations and trouble shooting on IBM{nbsp}Z, but only a subset of those that influence the installation program.
//If these are simply a subset, where are the rest documented?
