[id="advanced-installation-boot-options_{context}"]
= Advanced installation boot options

This section contains information about advanced installation boot options.

inst.kexec::
The `inst.kexec` option allows the installation program to use the `kexec` system call at the end of the installation, instead of performing a reboot. The `inst.kexec` option loads the new system immediately, and bypasses the hardware initialization normally performed by the BIOS or firmware.
+
[IMPORTANT]
======
This option is deprecated and available as a Technology Preview only. For information on Red Hat scope of support for Technology Preview features, see the link:https://access.redhat.com/support/offerings/techpreview[Technology Preview Features Support Scope] document.

When `kexec` is used, device registers which would normally be cleared during a full system reboot, might stay filled with data, which could potentially create issues for some device drivers.
======

////
inst.gpt::
The `inst.gpt` boot option forces the installation program to install partition information to a GUID Partition Table (GPT) instead of a Master Boot Record (MBR). This option is not valid on UEFI-based systems, unless they are in BIOS compatibility mode.

Normally, BIOS-based systems and UEFI-based systems in BIOS compatibility mode attempt to use the MBR schema for storing partitioning information, unless the disk is 232 sectors in size or larger. Disk sectors are typically 512 bytes in size, meaning that this is usually equivalent to 2 TiB. Using the `inst.gpt` boot option changes this behavior, allowing a GPT to be written to smaller disks.
NEED TO CHECK THIS WITH VENDY P. ON HER RETURN FROM PTO
////
inst.multilib::
Use the `inst.multilib` boot option to configure the system for multilib packages, that is, to allow installing 32-bit packages on a 64-bit AMD64 or Intel 64 system. Normally, on an AMD64 or Intel 64 system, only packages for this architecture (marked as x86_64) and packages for all architectures (marked as noarch) are installed. When you use the `inst.multilib` boot option, packages for 32-bit AMD or Intel systems (marked as i686) are automatically installed.
+
This applies only to packages directly specified in the `%packages` section. If a package is installed as a dependency, only the exact specified dependency is installed. For example, if you are installing the `bash` package which depends on the `glibc` package, the former is installed in multiple variants, while the latter is installed only in variants that the bash package requires.

selinux=0::
By default, the `selinux=0` boot option operates in permissive mode in the installation program, and in enforcing mode in the installed system. The `selinux=0` boot option disables the use of SELinux in the installation program and the installed system.
+
[NOTE]
====
The `selinux=0` and `inst.selinux=0` options are not the same. The `selinux=0` option disables the use of SELinux in the installation program and the installed system. The `inst.selinux=0` option disables SELinux only in the installation program. By default, SELinux operates in permissive mode in the installation program, so disabling SELinux has little effect.
====

inst.zram::
The `inst.zram` option controls the usage of zRAM swap during installation. The option creates a compressed block device inside the system RAM and uses it for swap space instead of the hard drive. This allows the installation program to run with less available memory than is possible without compression, and it might also make the installation faster.
By default, swap on zRAM is enabled on systems with 2 GiB or less RAM, and disabled on systems with more than 2 GiB of memory. You can use this option to change this behavior; on a system with more than 2 GiB RAM, use `inst.zram=1` to enable the feature, and on systems with 2 GiB or less memory, use `inst.zram=0` to disable the feature.

[discrete]
== Additional resources

* For a full list of boot options, see the link:https://github.com/rhinstaller/anaconda/blob/rhel-8.0/docs/boot-options.rst[upstream boot option] content.
