[id="kickstart-boot-options_{context}"]
= Kickstart boot options

This section contains information about the Kickstart boot options.

inst.ks=::
Use the `inst.ks=` boot option to define the location of a Kickstart file that you want to use to automate the installation. You can then specify locations using any of the `inst.repo` formats.
If you specify a device and not a path, the installation program looks for the Kickstart file in `/ks.cfg` on the device that you specify. If you use this option without specifying a device, the installation program uses the following option:
+
[subs="macros"]
----
inst.ks=nfs:next-server:/filename
----
+
In the previous example, _next-server_ is the DHCP next-server option or the IP address of the DHCP server itself, and _filename_ is the DHCP filename option, or _/kickstart/_. If the given file name ends with the `/` character, `ip-kickstart` is appended. The following table contains an example.
+
.Default Kickstart file location
[options="header"]
|===
| DHCP server address   | Client address  | Kickstart file location
| 192.168.122.1 | 192.168.122.100 | 192.168.122.1:/kickstart/192.168.122.100-kickstart
|===
+
If a volume with a label of `OEMDRV` is present, the installation program attempts to load a Kickstart file named `ks.cfg`. If your Kickstart file is in this location, you do not need to use the `inst.ks=` boot option.

inst.ks.all::
Specify this option to sequentially try multiple Kickstart file locations provided by multiple `inst.ks` options. The first successful location is used. This applies only to locations of type `http`, `https` or `ftp`, other locations are ignored.

inst.ks.sendmac::
Use the `inst.ks.sendmac` option to add headers to outgoing HTTP requests that contain the MAC addresses of all network interfaces. For example:
+
[subs="macros"]
----
X-RHN-Provisioning-MAC-0: eth0 01:23:45:67:89:ab
----
+
This can be useful when using `inst.ks=http` to provision systems.

inst.ks.sendsn::
Use the `inst.ks.sendsn` option to add a header to outgoing HTTP requests. This header contains the system serial number, read from `/sys/class/dmi/id/product_serial`. The header has the following syntax:
+
[subs="macros"]
----
X-System-Serial-Number: R8VA23D
----

[discrete]
== Additional resources

* For a full list of boot options, see the link:https://github.com/rhinstaller/anaconda/blob/rhel-8.0/docs/boot-options.rst[upstream boot option] content.
