[id="upgrade-or-clean-install_{context}"]
= Select upgrade or clean install

There are two procedures for upgrading your system to the next major version of {productname}.

.Clean install
A clean install requires backing up all data on the system, formatting disk partitions, performing an installation of {productname} from installation media, and restoring user data.

[NOTE]
====
A clean install is the recommended method for upgrading between major versions of {productname}.
====

.In-place upgrade
An in-place upgrade upgrades the system without removing previously installed versions of {productname}. This procedure requires the Preupgrade Assistant and the Upgrade Tool.

[WARNING]
====
Do not perform an in-place upgrade on a production system without first testing it on a cloned backup copy of the system. In-place upgrades are only supported on AMD64 and Intel 64 (x86_64) systems and on IBM Z. Additionally, only the Server base environment can be upgraded with the Upgrade Tool.
====

* *Preupgrade Assistant:* The Preupgrade Assistant is a diagnostics utility that assesses the system and identifies potential problems that may be encountered during or after the upgrade. It also applies minor fixes and modifications to the system. See the _Red Hat Enterprise Linux Migration Planning Guide_ for more information.

* *Upgrade Tool utility:* The Upgrade Tool utility downloaded the software packages and upgrades the system to the required version of {productname}. See the link:https://access.redhat.com/labs/rhelupgradehelper/[Hat Enterprise Linux Upgrade Helper] for more information.
