[id="planning-for-installation-on-ibm-z_{context}"]
= Planning for installation on IBM Z

== Pre-installation

{ProductName}{nbsp}8 runs on z13 or later IBM mainframe systems.

The installation process assumes that you are familiar with the IBM{nbsp}Z and can set up _logical partitions_ (LPARs) and z/VM guest virtual machines.

For installation of {ProductName} on IBM{nbsp}Z, Red{nbsp}Hat supports Direct Access Storage Device (DASD) and Fiber Channel Protocol (FCP) storage devices.

*Pre-installation decisions*

* Whether the operating system is to be run on an LPAR or as a z/VM guest operating system.

* If swap space is needed, and how much. Although it is recommended to assign enough memory to a z/VM guest virtual machine and let z/VM do the necessary swapping, there are cases where the amount of required RAM is hard to predict. Such instances should be examined on a case-by-case basis.

* Network configuration. {ProductName}{nbsp}8 for IBM{nbsp}Z supports the following network devices:
+
** Real and virtual _Open Systems Adapter_ (OSA)
+
** Real and virtual HiperSockets
+
** _LAN channel station_ (LCS) for real OSA

*Disk space*

You will need to calculate and allocate sufficient disk space on DASDs or SCSI disks.

* A minimum of 10{nbsp}GB is needed for a server installation,  20{nbsp}GB if you want to install all packages.

* Disk space is also required for any application data. After the installation, you can add or delete more DASD or SCSI disk partitions.

* The disk space used by the newly installed {ProductName} system (the Linux instance) must be separate from the disk space used by other operating systems you have installed on your system.

*RAM*

You will have to ensure enough RAM is available.

* 1{nbsp}GB is recommended for the Linux instance. With some tuning, an instance might run with as little as 512{nbsp}MB RAM.

* If installing from NFS, 1{nbsp}GB is sufficient. However, if installing from an HTTP or FTP source, 1.5{nbsp}GB is needed.

* Running at 512{nbsp}MB in text mode can be done only when installing from NFS.


[NOTE]
====
When initializing swap space on a Fixed Block Architecture (FBA) DASD using the [application]*SWAPGEN* utility, the [option]`FBAPART` option must be used.
====

[discrete]

==== Additional Resources

* For additional information on IBM{nbsp}Z, see link:++http://www.ibm.com/systems/z++[].
