[id="making-media_{context}"]
= Creating installation media

This section contains information about using the ISO image file that you downloaded in xref:standard-install:assembly_preparing-for-your-installation.adoc#downloading-beta-installation-images_preparing-for-your-installation[Downloading the installation ISO image]
to create bootable physical installation media, such as a USB, DVD, or CD.

For instructions on how to set up a _Preboot Execution Environment_ (PXE) server to perform a PXE-based installation over a network, see xref:advanced-install:assembly_preparing-for-a-network-install.adoc[Preparing to install from the network using PXE].

[NOTE]
====
By default, the [option]`inst.stage2=` boot option is used on the installation media and is set to a specific label, for example, [option]`inst.stage2=hd:LABEL=RHEL8\x86_64`. If you modify the default label of the file system containing the runtime image, or if you use a customized procedure to boot the installation system, you must verify that the label is set to the correct value.
====

See xref:advanced-install:assembly_kickstart-and-advanced-boot-options.adoc#installation-source-boot-options_kickstart-and-advanced-boot-options[Installation source boot options] for details.
