[id="creating-an-installation-source-on-http_{context}"]
= Creating an installation source using HTTP or HTTPS

Follow the steps in this procedure to create an installation source for a network-based installation using an installation tree, which is a directory containing extracted contents of the DVD1 ISO image and a valid [filename]`.treeinfo` file. The installation source is accessed over HTTP or HTTPS.

[discrete]
== Prerequisites

* You have administor level access to a server with {rel8}, and this server is on the same network as the system to be installed.
* You have downloaded a DVD1 ISO image. See xref:standard-install:assembly_preparing-for-your-installation.adoc#downloading-beta-installation-images_preparing-for-your-installation[Downloading the installation ISO image] for more information.
* You have created a bootable CD, DVD, or USB device from the image file. See xref:standard-install:assembly_preparing-for-your-installation.adoc#making-media_preparing-for-your-installation[Creating installation media] for more information.
* You have verified that your firewall allows the system you are installing to access the remote installation source. See xref:standard-install:assembly_preparing-for-your-installation.adoc#ports-for-network-based-installation_prepare-installation-source[Ports for network-based installation] for more information.

[discrete]
== Procedure

. Install the [package]`httpd` package:
+
[subs="quotes, macros, attributes"]
----
# yum install httpd
----
+
[WARNING]
====
If your Apache web server configuration enables SSL security, verify that you enable only the TLSv1 protocol, and disable SSLv2 and SSLv3. This is due to the POODLE SSL vulnerability (CVE-2014-3566). See https://access.redhat.com/solutions/1232413 for details.
====
+
[IMPORTANT]
====
If you use an HTTPS server with a self-signed certificate, you must boot the installation program with the [option]`noverifyssl` option.
====

. Copy the DVD1 ISO image to the HTTP(S) server.

. Mount the DVD1 ISO image, using the [command]`mount` command, to a suitable directory:
+
[subs="quotes, macros, attributes"]
----
# mkdir /mnt/centos8-install/
# mount -o loop,ro -t iso9660 _/image_directory/image.iso_ /mnt/centos8-install/
----
+
Replace _/image_directory/image.iso_ with the path to the DVD1 ISO image.

. Copy the files from the mounted image to the HTTP(S) server root. This command creates the `/var/www/html/centos8-install/` directory with the contents of the image.
+
[subs="quotes, macros, attributes"]
----
# cp -r /mnt/centos8-install/ /var/www/html/
----
+
This command creates the [literal]`/var/www/html/centos8-install/` directory with the content of the image. Note that some copying methods can skip the `.treeinfo` file which is required for a valid installation source. Running the `cp` command for whole directories as shown in this procedure will copy `.treeinfo` correctly.

. Start the `httpd` service:
+
[subs="quotes, macros, attributes"]
----
# systemctl start httpd.service
----
+
The installation tree is now accessible and ready to be used as the installation source.
+
[NOTE]
====
When configuring the installation source, use `http://` or `https://` as the protocol, the server host name or IP address, and the directory that contains the files from the ISO image, relative to the HTTP server root. For example, if you are using HTTP, the server host name is `myserver.example.com`, and you have copied the files from the image to `/var/www/html/centos8-install/`, specify `http://myserver.example.com/centos8-install/` as the installation source.
====


[discrete]
== Additional resources

* For more information about HTTP servers, see the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/deploying_different_types_of_servers/index/[_Deploying different types of servers in RHEL 8_] document.
