[id="persistently-adding-a-qeth-device_{context}"]
= Persistently adding a qeth device

To make your new `qeth` device persistent, you need to create the configuration file for your new interface. The network interface configuration files are placed in the `/etc/sysconfig/network-scripts/` directory.

The network configuration files use the naming convention `ifcfg-_device_pass:attributes[{blank}]`, where _device_ is the value found in the `if_name` file in the `qeth` group device that was created earlier, for example `enc9a0`. The [command]`cio_ignore` commands are handled transparently for persistent device configurations and you do not need to free devices from the ignore list manually.

If a configuration file for another device of the same type already exists, the simplest way to add the config file is to copy it to the new name and then edit it:

[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cd /etc/sysconfig/network-scripts
pass:quotes[`#`] cp ifcfg-enc9a0 ifcfg-enc600
....

To learn IDs of your network devices, use the [application]*lsqeth* utility:

[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] lsqeth -p
devices                    CHPID interface        cardtype       port chksum prio-q'ing rtr4 rtr6 lay'2 cnt
-------------------------- ----- ---------------- -------------- ---- ------ ---------- ---- ---- ----- -----
0.0.09a0/0.0.09a1/0.0.09a2 x00   enc9a0    Virt.NIC QDIO  0    sw     always_q_2 n/a  n/a  1     64
0.0.0600/0.0.0601/0.0.0602 x00   enc600    Virt.NIC QDIO  0    sw     always_q_2 n/a  n/a  1     64
....

If you do not have a similar device defined, you must create a new file. Use this example of `/etc/sysconfig/network-scripts/ifcfg-0.0.09a0` as a template:

[literal,subs="+quotes,verbatim"]
....
# IBM QETH
DEVICE=enc9a0
BOOTPROTO=static
IPADDR=10.12.20.136
NETMASK=255.255.255.0
ONBOOT=yes
NETTYPE=qeth
SUBCHANNELS=0.0.09a0,0.0.09a1,0.0.09a2
PORTNAME=OSAPORT
OPTIONS='layer2=1 portno=0'
MACADDR=02:00:00:23:65:1a
TYPE=Ethernet
....

Edit the new `ifcfg-0.0.0600` file as follows:

. Modify the `DEVICE` statement to reflect the contents of the `if_name` file from your `ccw` group.

. Modify the `IPADDR` statement to reflect the IP address of your new interface.

. Modify the `NETMASK` statement as needed.

. If the new interface is to be activated at boot time, then make sure `ONBOOT` is set to `yes`.

. Make sure the `SUBCHANNELS` statement matches the hardware addresses for your qeth device.

. Modify the `PORTNAME` statement or leave it out if it is not necessary in your environment.

. You can add any valid `sysfs` attribute and its value to the `OPTIONS` parameter. The {ProductName} installation program currently uses this to configure the layer mode (`layer2`) and the relative port number (`portno`) of `qeth` devices.
+
The `qeth` device driver default for OSA devices is now layer 2 mode. To continue using old `ifcfg` definitions that rely on the previous default of layer 3 mode, add `layer2=0` to the `OPTIONS` parameter.

`/etc/sysconfig/network-scripts/ifcfg-0.0.0600`

[literal,subs="+quotes,verbatim"]
....
# IBM QETH
DEVICE=enc600
BOOTPROTO=static
IPADDR=192.168.70.87
NETMASK=255.255.255.0
ONBOOT=yes
NETTYPE=qeth
SUBCHANNELS=0.0.0600,0.0.0601,0.0.0602
PORTNAME=OSAPORT
OPTIONS='layer2=1 portno=0'
MACADDR=02:00:00:b3:84:ef
TYPE=Ethernet
....

Changes to an `ifcfg` file only become effective after rebooting the system or after the dynamic addition of new network device channels by changing the system's I/O configuration (for example, attaching under z/VM). Alternatively, you can trigger the activation of a `ifcfg` file for network channels which were previously not active yet, by executing the following commands:

. Use the [command]`cio_ignore` utility to remove the network channels from the list of ignored devices and make them visible to Linux:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r read_device_bus_id,write_device_bus_id,data_device_bus_id
....
+
Replace _read_device_bus_id_,_write_device_bus_id_,_data_device_bus_id_ with the three device bus IDs representing a network device. For example, if the _read_device_bus_id_ is `0.0.0600`, the _write_device_bus_id_ is `0.0.0601`, and the _data_device_bus_id_ is `0.0.0602`:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`]  cio_ignore -r 0.0.0600,0.0.0601,0.0.0602
....

. To trigger the uevent that activates the change, issue:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo add > /sys/bus/ccw/devices/read-channel/uevent
....
+
For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo add > /sys/bus/ccw/devices/0.0.0600/uevent
....

. Check the status of the network device:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] lsqeth
....

. Now start the new interface:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] ifup enc600
....

. Check the status of the interface:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] ip addr show enc600
3: enc600:  <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
link/ether 3c:97:0e:51:38:17 brd ff:ff:ff:ff:ff:ff
inet 10.85.1.245/24 brd 10.34.3.255 scope global dynamic enc600
valid_lft 81487sec preferred_lft 81487sec
inet6 1574:12:5:1185:3e97:eff:fe51:3817/64 scope global noprefixroute dynamic
valid_lft 2591994sec preferred_lft 604794sec
inet6 fe45::a455:eff:d078:3847/64 scope link
valid_lft forever preferred_lft forever
....

. Check the routing for the new interface:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] ip route
default via 10.85.1.245 dev enc600  proto static  metric 1024
12.34.4.95/24 dev enp0s25  proto kernel  scope link  src 12.34.4.201
12.38.4.128 via 12.38.19.254 dev enp0s25  proto dhcp  metric 1
192.168.122.0/24 dev virbr0  proto kernel  scope link  src 192.168.122.1
....

. Verify your changes by using the `ping` utility to ping the gateway or another host on the subnet of the new device:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] ping -c 1 192.168.70.8
PING 192.168.70.8 (192.168.70.8) 56(84) bytes of data.
64 bytes from 192.168.70.8: icmp_seq=0 ttl=63 time=8.07 ms
....

. If the default route information has changed, you must also update `/etc/sysconfig/network` accordingly.
