[id="persistently-adding-an-lcs-device_{context}"]
= Persistently adding an LCS device

The [command]`cio_ignore` commands are handled transparently for persistent device configurations and you do not need to free devices from the ignore list manually.

To add an LCS device persistently, follow these steps:

. Create a configuration script as file in `/etc/sysconfig/network-scripts/` with a name like `ifcfg-_device_pass:attributes[{blank}]`, where _device_ is the value found in the `if_name` file in the `qeth` group device that was created earlier, for example `enc9a0`. The file should look similar to the following:
+
[literal,subs="+quotes,verbatim"]
....

# IBM LCS
DEVICE=enc9a0
BOOTPROTO=static
IPADDR=10.12.20.136
NETMASK=255.255.255.0
ONBOOT=yes
NETTYPE=lcs
SUBCHANNELS=0.0.09a0,0.0.09a1
PORTNAME=0
OPTIONS=''
TYPE=Ethernet
....

. Modify the value of `PORTNAME` to reflect the LCS port number (`portno`) you would like to use. You can add any valid lcs sysfs attribute and its value to the optional `OPTIONS` parameter. See <<sect-post-installation-qeth-device-persistent-s390>> for the syntax.

. Set the `DEVICE` parameter as follows:
+
[literal,subs="+quotes,verbatim,macros"]
....
DEVICE=enccwpass:quotes[_bus_ID_]
....

. Issue an [command]`ifup` command to activate the device:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] ifup encbus_ID
....

Changes to an `ifcfg` file only become effective after rebooting the system. You can trigger the activation of a `ifcfg` file for network channels by executing the following commands:

. Use the [command]`cio_ignore` utility to remove the LCS device adapter from the list of ignored devices and make it visible to Linux:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r read_device_bus_id,write_device_bus_id
....
+
Replace _read_device_bus_id_ and _write_device_bus_id_ with the device bus IDs of the LCS device. For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r 0.0.09a0,0.0.09a1
....

. To trigger the uevent that activates the change, issue:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo add > /sys/bus/ccw/devices/read-channel/uevent
....
+
For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo add > /sys/bus/ccw/devices/0.0.09a0/uevent
....
