[id='booting-the-installer-from-local-media_{context}']
= Booting the installation from a USB, CD, or DVD
//TODO: This isn't a procedure, came from alpha, needs to be changed.

Follow the steps in this procedure to boot the {productname} installation using a USB, CD, or DVD.
The following steps are generic. Consult your hardware manufacturer's documentation for specific instructions.

.Prerequisite

You have created bootable installation media (USB, CD or DVD). See xref:standard-install:assembly_preparing-for-your-installation.adoc#making-media_preparing-for-your-installation[Creating installation media] for more information.


.Procedure

. Power off the system to which you are installing {productname}.

. Disconnect any drives from the system.

. Power on the system.

. Insert the bootable installation media (USB, DVD, or CD).

. Power off the system but do not remove the boot media.

. Power on the system.
+
[NOTE]
====
You might need to press a specific key or combination of keys to boot from the media or configure the Basic Input/Output System (BIOS) of your system to boot from the media. For more information, see the documentation that came with your system.
====

. The *{productname} boot* window opens and displays information about a variety of available boot options.

. Use the arrow keys on your keyboard to select the boot option that you require, and press *Enter* to select the boot option.
The *Welcome to Red Hat Enterprise Linux* window opens and you can install {productname} using the graphical user interface.
+
[NOTE]
====
The installation program automatically begins if no action is performed in the boot window within 60 seconds.
====

. Optional: For UEFI-based systems, press *E* to edit the available boot options. For BIOS-based systems, press the *Tab* key on your keyboard to edit the available boot options. The boot window enters edit mode and you can change the predefined command line to add or remove boot options.

.. Press *Enter* to confirm your choice.



.Additional Resources
* For more information about installing {productname} using the Graphical User Interface, see xref:standard-install:assembly_graphical-installation.adoc[Installing using the Graphical User Interface].
* For more information about the list of available boot options you can use on the boot command line, see xref:standard-install:assembly_custom-boot-options.adoc[Boot options reference].
