[id="creating-an-installation-source_{context}"]
= Creating an installation source on an NFS server

Follow the steps in this procedure to place the installation source on an NFS server. Use this installation method to install multiple systems from a single source, without having to connect to physical media.

[discrete]
== Prerequisites

* You have administor level access to a server with {RHEL8}, and this server is on the same network as the system to be installed.
ifdef::installation-title[]
* You have downloaded a Binary DVD ISO image. See <<downloading-beta-installation-images_preparing-for-your-installation>> for more information.
* You have created a bootable CD, DVD, or USB device from the image file. See <<making-media_preparing-for-your-installation>> for more information.
* You have verified that your firewall allows the system you are installing to access the remote installation source. See <<ports-for-network-based-installation_prepare-installation-source>> for more information.
endif::[]
ifndef::installation-title[]
* You have downloaded a Binary DVD image. See link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/performing_a_standard_rhel_installation/index#downloading-beta-installation-images_preparing-for-your-installation[Downloading the installation ISO image] from the _Performing a standard RHEL installation_ document for more information.
* You have created a bootable CD, DVD, or USB device from the image file.  See link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/performing_a_standard_rhel_installation/index#making-media_preparing-for-your-installation[Creating installation media] from the _Performing a standard RHEL installation_ document for more information.
* You have verified that your firewall allows the system you are installing to access the remote installation source. See link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/performing_a_standard_rhel_installation/index#ports-for-network-based-installation_prepare-installation-source[Ports for network-based installation] from the _Performing a standard RHEL installation_ document for more information.
endif::[]



[discrete]
== Procedure

. Install the [package]`nfs-utils` package:
+
[subs="quotes, macros, attributes"]
----
# yum install nfs-utils
----

. Copy the Binary DVD ISO image to a directory on the NFS server.

. Open the [filename]`/etc/exports` file using a text editor and add a line with the following syntax:
+
[subs="quotes, macros, attributes"]
----
/__exported_directory__/ __clients__
----

.  Replace _/exported_directory/_ with the full path to the directory with the ISO image. Replace __clients__ with the host name or IP address of the target system, the subnetwork that all target systems can use to access the ISO image, or the asterisk sign (`*`) if you want to allow any system with network access to the NFS server to use the ISO image. See the `exports(5)` man page for detailed information about the format of this field.
+
A basic configuration that makes the `/rhel8-install/` directory available as read-only to all clients is:
+
[subs="quotes, macros, attributes"]
----
/rhel8-install *
----

. Save the [filename]`/etc/exports` file and exit the text editor.
. Start the nfs service:
+
[subs="quotes, macros, attributes"]
----
# systemctl start nfs-server.service
----
+
If the service was running before you changed the [filename]`/etc/exports` file, run the following command for the running NFS server to reload its configuration:
+
[subs="quotes, macros, attributes"]
----
# systemctl reload nfs-server.service
----
+
The ISO image is now accessible over NFS and ready to be used as an installation source.

[NOTE]
====
When configuring the installation source, use `nfs:` as the protocol, the server host name or IP address, the colon sign `(:)`, and the directory holding the ISO image. For example, if the server host name is `myserver.example.com` and you have saved the ISO image in `/rhel8-install/`, specify `nfs:myserver.example.com:/rhel8-install/` as the installation source.
====
