[id="completing-initial-setup_{context}"]
= Completing initial setup

This section contains information about how to complete initial setup on a {productname} 8 system.

[IMPORTANT]
====
If you selected the *Server with GUI* base environment during installation, the *Initial Setup* window opens the first time you reboot your system after the installation process is complete.
====

The information displayed in the *Initial Setup* window might vary depending on what was configured during installation. At a minimum, the *Licensing* and *Subscription Manager* options are displayed.


[discrete]
== Prerequisite

* You have completed the graphical installation according to the recommended workflow described on xref:standard-install:con_installation-workflow.adoc[Installation workflow].

[discrete]
== Procedure

. From the *Initial Setup* window, select *Licensing Information*.
+
The *License Agreement* window opens and displays the licensing terms for Red Hat Enterprise Linux.

. Review the license agreement and select the *I accept the license agreement* checkbox.
+
[NOTE]
====
You must accept the license agreement. Exiting *Initial Setup* without completing this step causes a system restart. When the restart process is complete, you are prompted to accept the license agreement again.
====

. Click *Done* to apply the settings and return to the *Initial Setup* window.
+
[NOTE]
====
If you did not configure network settings, you cannot register your system immediately. In this case, click *Finish Configuration*. {productname} 8 starts and you can login and activate access to the network
If you configured network settings, as described in xref:standard-install:assembly_graphical-installation.adoc#network-hostname_configuring-system-settings[Configuring network and host name options], you can register your system immediately, as shown in the following steps:
====
