[id="securing_{context}"]
= Securing your system

Complete the following security-related steps immediately after you install {productname}.

[discrete]
== Prerequisites

* You have completed the graphical installation according to the recommended workflow described in xref:standard-install:con_installation-workflow.adoc[Installation workflow].

[discrete]
== Procedure

. To update your system, run the following command as root:
+
[subs="quotes"]
----
# yum update
----

. Even though the firewall service, `firewalld`, is automatically enabled with the installation of {ProductName}, there are scenarios where it might be explicitly disabled, for example in a Kickstart configuration. In that scenario, it is recommended that you re-enable the firewall.
+
To start `firewalld`, run the following commands as root:
+
[subs="quotes"]
----
# systemctl start firewalld
# systemctl enable firewalld
----

. To enhance security, disable services that you do not need. For example, if your system has no printers installed, disable the cups service using the following command:
+
[subs="quotes"]
----
# systemctl mask cups
----
+
To review active services, run the following command:
+
[subs="quotes"]
----
$ systemctl list-units | grep service
----
