[id="powering-on-your-server-with-ipmi_{context}"]
= Powering on your server with IPMI

Intelligent Platform Management Interface (IPMI) is the default console to use when connecting to the OPAL firmware.

Use the default values for IPMI:

* Default user: `ADMIN`
* Default password: `admin`

[NOTE]
====
After your system powers on, the Petitboot interface loads. If you do not interrupt the boot process by pressing any key within 10 seconds, Petitboot automatically boots the first option.
To power on your server from a PC or notebook that is running Linux, follow these steps:
====

. Open a terminal program on your PC or notebook.

. To power on your server, run the following command:
+
[literal,subs="+quotes,verbatim"]
----
ipmitool -I lanplus -H _server_ip_address_ -U _ipmi_user_ -P ipmi_password chassis power on
----
+
where _server_ip_ipaddress_ is the IP address of the Power system and _ipmi_password_ is the password set up for IPMI.
+
[NOTE]
====
If your system is already powered on, continue to activate your IPMI console.
====

. Activate your IPMI console by running this command
+
[literal,subs="+quotes,verbatim"]
----
ipmitool -I lanplus -H _server_ip_address_ -U _ipmi_user_ -P _ipmi_password_ sol activate
----

[NOTE]
====
Use your keyboard up arrow to display the previous `ipmitool` command. You can edit previous commands to avoid typing the entire command again. If you need to power off or reboot your system, deactivate the console by running this command:

[literal,subs="+quotes,verbatim"]
----
ipmitool -I lanplus -H _server_ip_address_ -U _user-name_ -P _ipmi_password_ sol deactivate
----

To reboot the system, run this command:

[literal,subs="+quotes,verbatim"]
----
ipmitool -I lanplus -H _server_ip_address_ -U _user-name_ -P _ipmi_password_ chassis power reset
----
====
