[id="creating-an-installation-source-on-ftp_{context}"]
= Creating an installation source using FTP

Follow the steps in this procedure to create an installation source for a network-based installation using an installation tree, which is a directory containing extracted contents of the Binary DVD ISO image and a valid [filename]`.treeinfo` file. The installation source is accessed over FTP.

[discrete]
== Prerequisites

* You have administor level access to a server with {RHEL8}, and this server is on the same network as the system to be installed.
ifdef::installation-title[]
* You have downloaded a Binary DVD ISO image. See <<downloading-beta-installation-images_preparing-for-your-installation>> for more information.
* You have created a bootable CD, DVD, or USB device from the image file. See <<making-media_preparing-for-your-installation>> for more information.
* You have verified that your firewall allows the system you are installing to access the remote installation source. See <<ports-for-network-based-installation_prepare-installation-source>> for more information.
endif::[]
ifndef::installation-title[]
* You have downloaded a Binary DVD image. See link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/performing_a_standard_rhel_installation/index#downloading-beta-installation-images_preparing-for-your-installation[Downloading the installation ISO image] from the _Performing a standard RHEL installation_ document for more information.
* You have created a bootable CD, DVD, or USB device from the image file.  See link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/performing_a_standard_rhel_installation/index#making-media_preparing-for-your-installation[Creating installation media] from the _Performing a standard RHEL installation_ document for more information.
* You have verified that your firewall allows the system you are installing to access the remote installation source. See link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/performing_a_standard_rhel_installation/index#ports-for-network-based-installation_prepare-installation-source[Ports for network-based installation] from the _Performing a standard RHEL installation_ document for more information.
endif::[]

[discrete]
== Procedure

. Install the [package]`vsftpd` package by running the following command as root:
+
----
# yum install vsftpd
----

. Open and edit the [filename]`/etc/vsftpd/vsftpd.conf` configuration file in a text editor.

.. Change the line `anonymous_enable=NO` to `anonymous_enable=YES`

.. Change the line `write_enable=YES` to `write_enable=NO`.

.. Add lines `pasv_min_port=__min_port__` and `pasv_max_port=__max_port__`. Replace __min_port__ and __max_port__ with the port number range used by FTP server in passive mode, e. g. `10021` and `10031`.
+
This step can be necessary in network environments featuring various firewall/NAT setups.

.. Optionally, add custom changes to your configuration. For available options, see the *vsftpd.conf(5)* man page. This procedure assumes that default options are used.
+
[WARNING]
====
If you configured SSL/TLS security in your [filename]`vsftpd.conf` file, ensure that you enable only the TLSv1 protocol, and disable SSLv2 and SSLv3. This is due to the POODLE SSL vulnerability (CVE-2014-3566). See https://access.redhat.com/solutions/1234773 for details.
====

. Configure the server firewall.

.. Enable the firewall:
+
----
# systemctl enable firewalld
# systemctl start firewalld
----

.. Enable in your firewall the FTP port and port range from previous step:
+
[subs="quotes"]
----
# firewall-cmd --add-port __min_port__-__max_port__/tcp --permanent
# firewall-cmd --add-service ftp --permanent
# firewall-cmd --reload
----
+
Replace __min_port__-__max_port__ with the port numbers you entered into the [filename]`/etc/vsftpd/vsftpd.conf` configuration file.

. Copy the Binary DVD ISO image to the FTP server.

. Mount the Binary DVD ISO image, using the mount command, to a suitable directory:
+
[subs="quotes"]
----
# mkdir /mnt/rhel8-install
# mount -o loop,ro -t iso9660 __/image-directory/image.iso__ /mnt/rhel8-install
----
+
Replace __/image-directory/image.iso__ with the path to the Binary DVD ISO image.

. Copy the files from the mounted image to the FTP server root:
+
[subs="quotes"]
----
# mkdir /var/ftp/rhel8-install
# cp -r /mnt/rhel8-install/ /var/ftp/
----
+
This command creates the [literal]`/var/ftp/rhel8-install/` directory with the content of the image. Note that some copying methods can skip the `.treeinfo` file which is required for a valid installation source. Running the `cp` command for whole directories as shown in this procedure will copy `.treeinfo` correctly.

. Make sure that the correct SELinux context and access mode is set on the copied content:
+
----
# restorecon -r /var/ftp/rhel8-install
# find /var/ftp/rhel8-install -type f -exec chmod 444 {} \;
# find /var/ftp/rhel8-install -type d -exec chmod 755 {} \;
----

. Start the `vsftpd` service:
+
----
# systemctl start vsftpd.service
----
+
If the service was running before you changed the [filename]`/etc/vsftpd/vsftpd.conf` file, restart the service to load the edited file:
+
----
# systemctl restart vsftpd.service
----
+
The installation tree is now accessible and ready to be used as the installation source.
+
[NOTE]
====
When configuring the installation source, use `ftp://` as the protocol, the server host name or IP address, and the directory in which you have stored the files from the ISO image, relative to the FTP server root. For example, if the server host name is `myserver.example.com` and you have copied the files from the image to `/var/ftp/rhel8-install/`, specify `ftp://myserver.example.com/rhel8-install/` as the installation source.
====

