[id="installing-under-z-vm_{context}"]
= Installing under z/VM

Use the [application]*x3270* or [application]*c3270* terminal emulator, to log in to z/VM from other Linux systems, or use the IBM 3270 terminal emulator on the IBM{nbsp}Z Hardware Management Console (HMC). If you are running Microsoft Windows operating system, there are several options available, and can be found through an internet search. A free native Windows port of [application]*c3270* called [application]*wc3270* also exists.

When installing under z/VM, you can boot from:

* The z/VM virtual reader

* A DASD or an FCP-attached SCSI device prepared with the [application]*zipl* boot loader

* An FCP-attached SCSI DVD drive

. Log on to the z/VM guest virtual machine chosen for the Linux installation.

[NOTE]
====

If your 3270 connection is interrupted and you cannot log in again because the previous session is still active, you can replace the old session with a new one by entering the following command on the z/VM logon screen:

[literal,subs="+quotes,verbatim,macros"]
....
[command]`logon _user_ here`
....

Replace _user_ with the name of the z/VM guest virtual machine. Depending on whether an external security manager, for example RACF, is used, the logon command might vary.

====

If you are not already running [application]*CMS* (single-user operating system shipped with z/VM) in your guest, boot it now by entering the command:

[literal,subs="+quotes,verbatim,macros"]
....
[command]`cp ipl cms`
....

Be sure not to use CMS disks such as your A disk (often device number 0191) as installation targets. To find out which disks are in use by CMS, use the following query:

[literal,subs="+quotes,verbatim,macros"]
....
[command]`query disk`
....

You can use the following CP (z/VM Control Program, which is the z/VM hypervisor) query commands to find out about the device configuration of your z/VM guest virtual machine:

* Query the available main memory, which is called _storage_ in IBM{nbsp}Z terminology. Your guest should have at least 1 GB of main memory.
+
[literal,subs="+quotes,verbatim,macros"]
....
[command]`cp query virtual storage`
....

* Query available network devices by type:
+
[command]`osa`::
+
OSA - CHPID type OSD, real or virtual (VSWITCH or GuestLAN), both in QDIO mode
+
[command]`hsi`::
+
HiperSockets - CHPID type IQD, real or virtual (GuestLAN type Hipers)
+
[command]`lcs`::
+
LCS - CHPID type OSE
+
For example, to query all of the network device types mentioned above, run:
+
[literal,subs="+quotes,verbatim,macros"]
....
[command]`cp query virtual osa`
....

* Query available DASDs. Only those that are flagged `RW` for read-write mode can be used as installation targets:
+
[literal,subs="+quotes,verbatim,macros"]
....
[command]`cp query virtual dasd`
....

* Query available FCP channels:
+
[literal,subs="+quotes,verbatim,macros"]
....
[command]`cp query virtual fcp`
....
