[id="resuming-an-interrupted-download-attempt_{context}"]
= Resuming an interrupted download attempt

You can resume an interrupted download using the [command]`curl` command.

.Prerequisite
You have navigated to the *Product Downloads* section of the Red Hat Customer Portal at link:https://access.redhat.com/downloads[], and selected the required variant, version, and architecture. You have right-clicked on the required ISO file, and selected *Copy Link Location* to copy the URL of the ISO image file to your clipboard.

.Procedure

. Download the ISO image from the new link. Add the `--continue-at -` option to automatically resume the download:
+
[subs="quotes"]
----
$ curl --output _directory-path/filename.iso_ _'new_copied_link_location'_ --continue-at -
----
. Use a checksum utility such as [application]*sha256sum* to verify the integrity of the image file after the download finishes:
+
[subs="quotes"]
....
$ sha256sum _rhel-8.0-x86_64-dvd.iso_
			_`85a...46c  rhel-8.0-x86_64-dvd.iso`_
....
+
Compare the output with reference checksums provided on the {ProductName} *Product Download* web page.
+
// Similar tools are available for link:http://www.labtestproject.com/files/win/sha256sum/sha256sum.exe[Microsoft Windows] and link:++https://itunes.apple.com/us/app/hashtab/id517065482++[Mac OS X]. You can also use the installation program to verify the media when starting the installation.


.Resuming an interrupted download attempt
====
The following is an example of a [command]`curl` command for a partially downloaded ISO image:

// maybe needs literal or sth in []

[subs="quotes"]
....
$ curl --output __rhel-8.0-x86_64-dvd.iso 'https://access.cdn.redhat.com//content/origin/files/sha256/85/85a...46c/rhel-8.0-x86_64-dvd.iso?_auth_=141...963' --continue-at -
....
====
