[id="completing-the-prerequisites-and-booting-your-firmware_{context}"]
= Completing the prerequisites and booting your firmware

Before you power on the system, ensure that you have the following items:

* Ethernet cable
* VGA monitor. The VGA resolution must be set to 1024x768-60Hz.
* USB Keyboard
* Power cords and outlet for your system

These instructions require that you have a network server set up with Red Hat Enterprise Linux 7.x. Download Red Hat Enterprise Linux 7.x LE ALT at link:https://wiki.centos.org/Download[].

. Take the link for *Downloads for Red Hat Enterprise Linux for Power, little endian*.

. Log into your Red Hat account (if you have not already done so). Select *Red Hat Enterprise Linux for Power 9* from the Product Variant list.

. Look for the Red Hat Enterprise Linux for Power 9 (v. 7.x for ppc64le) ISO file. The downloaded ISO file will include *_centos-alt......iso_* rather than *_centos....iso_* in the path name.

Complete these steps:

* If your system belongs in a rack, install your system into that rack. For instructions, see IBM Power Systems information at link:https://www.ibm.com/support/knowledgecenter/POWER9/p9hdx/POWER9welcome.htm[].

* Connect an Ethernet cable to the embedded Ethernet port next to the serial port on the back of your system. Connect the other end to your network.

* Connect your VGA monitor to the VGA port on back of system.

* Connect your USB keyboard to an available USB port.

* Connect the power cords to the system and plug them into the outlets.

At this point, your firmware is booting. Wait for the green LED on the power button to start flashing, indicating that it is ready to use. If your system does not have a green LED indicator light, then wait 1 to 2 minutes.
