[id='booting-from-the-network-using-an-installation-server_{context}']
= Booting from the network using an installation server

// For network boot, you need a properly configured server, and a network interface in your computer that can support an installation server. For information on how to configure an installation server, see <<sect-network-boot-setup-ppc-grub2>>.

Configure the computer to boot from the network interface by selecting [option]`Select Boot Options` in the SMS menu, then [option]`Select Boot/Install Device`. Finally, select your network device from the list of available devices.

Once you properly configure booting from an installation server, the computer can boot the {ProductName} installation system without any other media.

To boot a computer from a server:

.How to Start the Installation Program from the Network
. Ensure that the network cable is attached. The link indicator light on the network socket should be lit, even if the computer is not switched on.

. Switch on the computer.

. Networking setup and diagnostic information usually appears before your computer connects to the server, although this depends on the hardware in use. Then you will see a menu with options specifying how the network boot server is setup. Press the number key that corresponds to the desired option. In case you are not sure which option you should select, ask your server administrator.

If your system does not boot from the network installation server, ensure that the SMS is configured to boot first from the correct network interface. See your hardware's documentation for more information.

[IMPORTANT]
====

Use the `vmlinuz` and `initrd.img` images to boot your system over a network.

====
