[id="post-installation-kickstart-section-options_{context}"]
= Post-installation Kickstart section options

The following options can be used to change the behavior of post-installation scripts. To use an option, append it to the `%post` line at the beginning of the script. For example:

----
%post --interpreter=/usr/libexec/platform-python
-- Python script omitted --
%end
----

[option]`--interpreter=`::
Allows you to specify a different scripting language, such as Python. For example:
+
----
%post --interpreter=/usr/libexec/platform-python
----
+
Any scripting language available on the system can be used; in most cases, these are `/usr/bin/sh`, `/usr/bin/bash`, and `/usr/libexec/platform-python`.
+
Note that the `platform-python` interpreter uses Python version 3.6. You must change your Python scripts from previous {ProductName}} versions for the new path and version. Additionally, `platform-python` is meant for system tools: Use the `python36` package outside the installation environment. For more details about Python, see link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/using-python3_configuring-basic-system-settings#introduction-to-python_using-python3[Introduction to Python] in _Configuring basic system settings in RHEL 8_.

[option]`--nochroot`::
Allows you to specify commands that you would like to run outside of the chroot environment.
+
The following example copies the file /etc/resolv.conf to the file system that was just installed.
+
----
%post --nochroot
cp /etc/resolv.conf /mnt/sysimage/etc/resolv.conf
%end
----

[option]`--erroronfail`::
Display an error and halt the installation if the script fails. The error message will direct you to where the cause of the failure is logged.

[option]`--log=`::
Logs the script's output into the specified log file. Note that the path of the log file must take into account whether or not you use the `--nochroot` option. For example, without `--nochroot`:
+
----
%post --log=/root/ks-post.log
----
+
and with `--nochroot`:
+
----
%post --nochroot --log=/mnt/sysimage/root/ks-post.log
----
