[id="kickstart-error-handling-section_{context}"]
= Kickstart error handling section

Starting with {RHEL} 7, Kickstart installations can contain custom scripts which are run when the installation program encounters a fatal error. For example, an error in a package that has been requested for installation, failure to start VNC when specified, or an error when scanning storage devices. Installation cannot continue after such an error has occured. The installation program will run all `%onerror` scripts in the order they are provided in the Kickstart file. In addition, `%onerror` scripts will be run in the event of a traceback.

Each `%onerror` script is required to end with `%end`.

Error handling sections accept the following options:

[option]`--erroronfail`::
Display an error and halt the installation if the script fails. The error message will direct you to where the cause of the failure is logged.

[option]`--interpreter=`::
Allows you to specify a different scripting language, such as Python. For example:
+
----
%onerror --interpreter=/usr/libexec/platform-python
----
+
Any scripting language available on the system can be used; in most cases, these are `/usr/bin/sh`, `/usr/bin/bash`, and `/usr/libexec/platform-python`.
+
Note that the `platform-python` interpreter uses Python version 3.6. You must change your Python scripts from previous {ProductName} versions for the new path and version. Additionally, `platform-python` is meant for system tools: Use the `python36` package outside the installation environment. For more details about Python, see link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/using-python3_configuring-basic-system-settings#introduction-to-python_using-python3[Introduction to Python in RHEL 8] in _Configuring basic system settings_.

[option]`--log=`::
Logs the script's output into the specified log file.
