[id="reboot_{context}"]
= reboot

The [command]`reboot` Kickstart command is optional. It instructs the installation program to reboot after the installation is successfully completed (no arguments). Normally, Kickstart displays a message and waits for the user to press a key before rebooting.


.Options

* [command]`--eject` - Attempt to eject the bootable media (DVD, USB, or other media) before rebooting.

* [command]`--kexec` - Uses the `kexec` system call instead of performing a full reboot, which immediately loads the installed system into memory, bypassing the hardware initialization normally performed by the BIOS or firmware.
+
[IMPORTANT]
======
This option is deprecated.

When `kexec` is used, device registers (which would normally be cleared during a full system reboot) might stay filled with data, which could potentially create issues for some device drivers.
======


.Notes

* Use of the [command]`reboot` option __might__ result in an endless installation loop, depending on the installation media and method.

* The [command]`reboot` option is equivalent to the [command]`shutdown -r` command. For more details, see the _shutdown(8)_ man page.

* Specify [command]`reboot` to automate installation fully when installing in command line mode on IBM{nbsp}Z.

* For other completion methods, see the [command]`halt`, [command]`poweroff`, and [command]`shutdown` Kickstart options. The [command]`halt` option is the default completion method if no other methods are explicitly specified in the Kickstart file.
