[id="volgroup_{context}"]
= volgroup

The [command]`volgroup` Kickstart command is optional. It creates a Logical Volume Management (LVM) group.

.Syntax

[subs="quotes,macros"]
----
[command]``volgroup __name__ __partition__ [__options__]``
----

// For a detailed partitioning example including [command]`volgroup`, see xnotref:sect-kickstart-partitioning-example[].

.Options

* [option]`--noformat` - Use an existing volume group and do not format it.

* [option]`--useexisting` - Use an existing volume group and reformat it. If you use this option, do not specify a __partition__. For example:
+
[subs="quotes,macros"]
----
[command]`volgroup rhel00 --useexisting --noformat`
----

* [option]`--pesize=` - Set the size of the volume group's physical extents in KiB. The default value is 4096 (4 MiB), and the minimum value is 1024 (1 MiB).

* [option]`--reserved-space=` - Specify an amount of space to leave unused in a volume group in MiB. Applicable only to newly created volume groups.

* [option]`--reserved-percent=` - Specify a percentage of total volume group space to leave unused. Applicable only to newly created volume groups.


.Notes

* Create the partition first, then create the logical volume group, and then create the logical volume. For example:
+
[subs="quotes,macros"]
----
[command]`part pv.01 --size 10000`
[command]`volgroup volgrp pv.01 `
[command]`logvol / --vgname=volgrp --size=2000 --name=root`
----

* Do not use the dash (`-`) character in logical volume and volume group names when installing {RHEL} using Kickstart. If this character is used, the installation finishes normally, but the [filename]`/dev/mapper/` directory will list these volumes and volume groups with every dash doubled. For example, a volume group named `volgrp-01` containing a logical volume named `logvol-01` will be listed as [filename]`/dev/mapper/volgrp--01-logvol--01`.
+
This limitation only applies to newly created logical volume and volume group names. If you are reusing existing ones using the [option]`--noformat` option, their names will not be changed.

