[id="user_{context}"]
= user

The [command]`user` Kickstart command is optional. It creates a new user on the system.

.Syntax

[subs="quotes,macros"]
----
[command]``user --name=__username__ [__options__]``
----

.Mandatory options

* [option]`--name=` - Provides the name of the user. This option is required.

.Optional options

* [option]`--gecos=` - Provides the GECOS information for the user. This is a string of various system-specific fields separated by a comma. It is frequently used to specify the user's full name, office number, and so on. See the `passwd(5)` man page for more details.

* [option]`--groups=` - In addition to the default group, a comma separated list of group names the user should belong to. The groups must exist before the user account is created. See the [command]`group` command.

* [option]`--homedir=` - The home directory for the user. If not provided, this defaults to [filename]`/home/__username__`.

* [option]`--lock` - If this option is present, this account is locked by default. This means that the user will not be able to log in from the console. This option will also disable the [GUI]*Create User* screens in both the graphical and text-based manual installation.

* [option]`--password=` - The new user's password. If not provided, the account will be locked by default.

* [option]`--iscrypted` - If this option is present, the password argument is assumed to already be encrypted. This option is mutually exclusive with [option]`--plaintext`. To create an encrypted password, you can use python:
+
[subs="quotes,macros"]
----
$ [command]`python -c 'import crypt,getpass;pw=getpass.getpass();print(crypt.crypt(pw) if (pw==getpass.getpass("Confirm: ")) else exit())'`
----
+
This generates a sha512 crypt-compatible hash of your password using a random salt.

* [option]`--plaintext` - If this option is present, the password argument is assumed to be in plain text. This option is mutually exclusive with [option]`--iscrypted`

* [option]`--shell=` - The user's login shell. If not provided, the system default is used.

* [option]`--uid=` - The user's UID (User ID). If not provided, this defaults to the next available non-system UID.

* [option]`--gid=` - The GID (Group ID) to be used for the user's group. If not provided, this defaults to the next available non-system group ID.

.Notes

* Consider using the [option]`--uid` and [option]`--gid` options to set IDs of regular users and their default groups at range starting at `5000` instead of `1000`. That is because the range reserved for system users and groups, `0`-`999`, might increase in the future and thus overlap with IDs of regular users.
+
For changing the minimum UID and GID limits after the installation, which ensures that your chosen UID and GID ranges are applied automatically on user creation, see the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/configuring_basic_system_settings/#sec-setting-default-permissions-for-new-files-using-umask[Setting default permissions for new files using umask] section of the __Configuring basic system settings__ document.


* Files and directories are created with various permissions, dictated by the application used to create the file or directory. For example, the [command]`mkdir` command creates directories with all permissions enabled. However, applications are prevented from granting certain permissions to newly created files, as specified by the `user file-creation mask` setting.
+
The `user file-creation mask` can be controlled with the [command]`umask` command. The default setting of the `user file-creation mask` for new users is defined by the `UMASK` variable in the [filename]`/etc/login.defs` configuration file on the installed system. If unset, it defaults to `022`. This means that by default when an application creates a file, it is prevented from granting write permission to users other than the owner of the file. However, this can be overridden by other settings or scripts. More information can be found in the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/configuring_basic_system_settings/#sec-setting-default-permissions-for-new-files-using-umask[Setting default permissions for new files using umask] section of the __Configuring basic system settings__ document.

