[id="logvol_{context}"]
= logvol

The [command]`logvol` Kickstart command is optional. It creates a logical volume for Logical Volume Management (LVM).


.Syntax

[subs="quotes,macros"]
----
[command]``logvol __mntpoint__ --vgname=__name__ --name=__name__ [__options__]``
----

// For a detailed example of [command]`logvol` in action, see xnotref:sect-kickstart-partitioning-example[].


.Mandatory options

* The __mntpoint__ is where the partition is mounted and must be of one of the following forms:
+
======
* [filename]`/__path__`
+
For example, [filename]`/` or [filename]`/home`

* `swap`
+
The partition is used as swap space.
+
To determine the size of the swap partition automatically, use the [option]`--recommended` option:
+
[subs="quotes,macros"]
----
`swap --recommended`
----
+
To determine the size of the swap partition automatically and also allow extra space for your system to hibernate, use the [option]`--hibernation` option:
+
[subs="quotes,macros"]
----
`swap --hibernation`
----
+
The size assigned will be equivalent to the swap space assigned by [option]`--recommended` plus the amount of RAM on your system.
+
For the swap sizes assigned by these commands, see xref:assembly_partitioning-reference.adoc#recommended-partitioning-scheme_partitioning-reference[Recommended partitioning scheme] for AMD64, Intel 64, and 64-bit ARM systems.
+
//, xnotref:sect-recommended-partitioning-scheme-ppc[] for IBM Power{nbsp}Systems servers, and xnotref:sect-recommended-partitioning-scheme-s390[] for IBM{nbsp}Z.
======

* [option]`--vgname=__name__` - name of the volume group.

* [option]`--name=__name__` - name of the logical volume.


.Optional options

* [option]`--noformat` - Use an existing logical volume and do not format it.

* [option]`--useexisting` - Use an existing logical volume and reformat it.

* [option]`--fstype=` - Sets the file system type for the logical volume. Valid values are `xfs`, `ext2`, `ext3`, `ext4`, `swap`, and `vfat`.

* [option]`--fsoptions=` - Specifies a free form string of options to be used when mounting the filesystem. This string will be copied into the [filename]`/etc/fstab` file of the installed system and should be enclosed in quotes.

* [option]`--mkfsoptions=` - Specifies additional parameters to be passed to the program that makes a filesystem on this partition. No processing is done on the list of arguments, so they must be supplied in a format that can be passed directly to the mkfs program. This means multiple options should be comma-separated or surrounded by double quotes, depending on the filesystem.

* [option]`--fsprofile=` - Specifies a usage type to be passed to the program that makes a filesystem on this partition. A usage type defines a variety of tuning parameters to be used when making a filesystem. For this option to work, the filesystem must support the concept of usage types and there must be a configuration file that lists valid types. For `ext2`, `ext3`, and `ext4`, this configuration file is `/etc/mke2fs.conf`.

* [option]`--label=` - Sets a label for the logical volume.

* [option]`--grow` - Tells the logical volume to grow to fill available space (if any), or up to the maximum size setting, if one is specified.  A minimum size must be given, using either the [option]`--percent=` option or the [option]`--size=` option.

* [option]`--size=` - The size of the logical volume in MiB. This option cannot be used together with the [option]`--percent=` option.

* [option]`--percent=` - The size of the logical volume, as a percentage of the free space in the volume group after any statically-sized logical volumes are taken into account. This option cannot be used together with the [option]`--size=` option.
+
[IMPORTANT]
========
When creating a new logical volume, you must either specify its size statically using the [option]`--size=` option, or as a percentage of remaining free space using the [option]`--percent=` option. You cannot use both of these options on the same logical volume.
========

* [option]`--maxsize=` - The maximum size in MiB when the logical volume is set to grow. Specify an integer value here such as `500` (do not include the unit).

* [option]`--recommended` - Use this option when creating a logical volume to determine the size of this volume automatically, based on your system's hardware. For details about the recommended scheme, see xref:assembly_partitioning-reference.adoc#recommended-partitioning-scheme_partitioning-reference[Recommended partitioning scheme] for AMD64, Intel 64, and 64-bit ARM systems.
+
//, xnotref:sect-recommended-partitioning-scheme-ppc[] for IBM Power{nbsp}Systems, and xnotref:sect-recommended-partitioning-scheme-s390[] for IBM{nbsp}Z.

* [option]`--resize` - Resize a logical volume. If you use this option, you must also specify [option]`--useexisting` and [option]`--size`.

* [option]`--encrypted` - Specifies that this logical volume should be encrypted with Linux Unified Key Setup (LUKS), using the passphrase provided in the [option]`--passphrase=` option. If you do not specify a passphrase, the installation program uses the default, system-wide passphrase set with the [command]`autopart --passphrase` command, or stops the installation and prompts you to provide a passphrase if no default is set.
+
[NOTE]
========
When encrypting one or more partitions, Anaconda attempts to gather 256 bits of entropy to ensure the partitions are encrypted securely. Gathering entropy can take some time - the process will stop after a maximum of 10 minutes, regardless of whether sufficient entropy has been gathered.

The process can be sped up by interacting with the installation system (typing on the keyboard or moving the mouse). If you are installing in a virtual machine, you can also attach a `virtio-rng` device (a virtual random number generator) to the guest.
========

* [option]`--passphrase=` - Specifies the passphrase to use when encrypting this logical volume. You must use this option together with the [option]`--encrypted` option; it has no effect by itself.

* [option]`--cipher=` - Specifies the type of encryption to use if the Anaconda default `aes-xts-plain64` is not satisfactory. You must use this option together with the [option]`--encrypted` option; by itself it has no effect. Available types of encryption are listed in the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/index[Security hardening in RHEL 8] document, but {RH} strongly recommends using either `aes-xts-plain64` or `aes-cbc-essiv:sha256`.

* [option]`--escrowcert=__URL_of_X.509_certificate__` - Store data encryption keys of all encrypted volumes as files in [filename]`/root`, encrypted using the X.509 certificate from the URL specified with __URL_of_X.509_certificate__. The keys are stored as a separate file for each encrypted volume. This option is only meaningful if [option]`--encrypted` is specified.

* [option]`--luks-version=__LUKS_VERSION__` - Specifies which version of LUKS format should be used to encrypt the filesystem. This option is only meaningful if [option]`--encrypted` is specified.

* [option]`--backuppassphrase` - Add a randomly-generated passphrase to each encrypted volume. Store these passphrases in separate files in [filename]`/root`, encrypted using the X.509 certificate specified with [option]`--escrowcert`. This option is only meaningful if [option]`--escrowcert` is specified.

* [option]`--pbkdf=_PBKDF_` - Sets Password-Based Key Derivation Function (PBKDF) algorithm for LUKS keyslot. See also the man page _cryptsetup(8)_. This option is only meaningful if [option]`--encrypted` is specified.

* [option]`--pbkdf-memory=__PBKDF_MEMORY__` - Sets the memory cost for PBKDF.  See also the man page _cryptsetup(8)_. This option is only meaningful if [option]`--encrypted` is specified.

* [option]`--pbkdf-time=__PBKDF_TIME__` - Sets the number of milliseconds to spend with PBKDF passphrase processing. See also [option]`--iter-time` in the man page _cryptsetup(8)_. This option is only meaningful if [option]`--encrypted` is specified, and is mutually exclusive with [option]`--pbkdf-iterations`.

* [option]`--pbkdf-iterations=__PBKDF_ITERATIONS__` - Sets the number of iterations directly and avoids PBKDF benchmark. See also [option]`--pbkdf-force-iterations` in the man page _cryptsetup(8)_. This option is only meaningful if [option]`--encrypted` is specified, and is mutually exclusive with [option]`--pbkdf-time`.

* [option]`--thinpool` - Creates a thin pool logical volume. (Use a mount point of `none`)

* [option]`--metadatasize=__size__` - Specify the metadata area size (in MiB) for a new thin pool device.

* [option]`--chunksize=__size__` - Specify the chunk size (in KiB) for a new thin pool device.

* [option]`--thin` - Create a thin logical volume. (Requires use of [option]`--poolname`)

* [option]`--poolname=__name__` - Specify the name of the thin pool in which to create a thin logical volume. Requires the [option]`--thin` option.

* [option]`--profile=__name__` - Specify the configuration profile name to use with thin logical volumes. If used, the name will also be included in the metadata for the given logical volume. By default, the available profiles are `default` and `thin-performance` and are defined in the [filename]`/etc/lvm/profile/` directory. See the `lvm(8)` man page for additional information.

* [option]`--cachepvs=` - A comma-separated list of physical volumes which should be used as a cache for this volume.

* [option]`--cachemode=` - Specify which mode should be used to cache this logical volume - either `writeback` or `writethrough`.
+
[NOTE]
========
For more information about cached logical volumes and their modes, see the `lvmcache(7)` man page.
========

* [option]`--cachesize=` - Size of cache attached to the logical volume, specified in MiB. This option requires the [option]`--cachepvs=` option.


.Notes

* Do not use the dash (`-`) character in logical volume and volume group names when installing {RHEL} using Kickstart. If this character is used, the installation finishes normally, but the [filename]`/dev/mapper/` directory will list these volumes and volume groups with every dash doubled. For example, a volume group named `volgrp-01` containing a logical volume named `logvol-01` will be listed as [filename]`/dev/mapper/volgrp--01-logvol--01`.
+
This limitation only applies to newly created logical volume and volume group names. If you are reusing existing ones using the [option]`--noformat` option, their names will not be changed.


.Examples

* Create the partition first, create the logical volume group, and then create the logical volume:
+
[subs="quotes,macros"]
----
[command]`part pv.01 --size 3000`
[command]`volgroup myvg pv.01`
[command]`logvol / --vgname=myvg --size=2000 --name=rootvol`
----

* Create the partition first, create the logical volume group, and then create the logical volume to occupy 90% of the remaining space in the volume group:

[subs="quotes,macros"]
----
[command]`part pv.01 --size 1 --grow`
[command]`volgroup myvg pv.01`
[command]`logvol / --vgname=myvg --name=rootvol --percent=90`
----


.Additional resources

* For more information regarding LVM, see the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_logical_volumes/index[Configuring and managing logical volumes in RHEL 8] document.

* If you lose the LUKS passphrase, any encrypted partitions and their data is completely inaccessible. There is no way to recover a lost passphrase. However, you can save encryption passphrases with the [option]`--escrowcert` and create backup encryption passphrases with the [option]`--backuppassphrase` options.
