[id="switching-module-streams-temporarily-to-examine-packages_{context}"]
= Switching module streams temporarily to examine packages

Because module streams act as filters on top of repositories, packages in currently inactive streams are not known to the system at all. In order to examine these packages available in inactive streams, the streams must be temporarily enabled so that the [command]`yum` tool can read metadata of these packages. If content is already installed from different streams of the same modules, the streams must be temporarily switched.

// see also https://bugzilla.redhat.com/show_bug.cgi?id=1629667


.Prerequisites


* A module stream must be active, and another stream of the module must exist.

ifdef::appstream-book[]
* You must understand xref:modular-dependencies-and-stream-changes_{context}[modular dependency resolution].
endif::[]
ifndef::appstream-book[]
* You must understand modular dependency resolution.
endif::[]

* Keep notes of the changes you are making so that you can undo them.

* Remember that modular dependencies may prevent you from completing this procedure.



.Procedure

. Enable the module stream to examine:
+
[subs="quotes"]
----
# yum module enable __module-name__:__other-stream__
----
+
This does not change the installed packages.
+
Note carefully which further streams were enabled as dependencies, and which streams were enabled before.
+
IMPORTANT: In some cases, it might be impossible to switch the stream due to modular dependencies.

. Query the packages provided by this stream.

. Return the module to its previous state:
+
====
* If no stream of that module was enabled, reset the module:
+
[subs="quotes"]
----
# yum module reset __module-name__
----

* If some stream of the module was enabled, enable that stream:
+
[subs="quotes"]
----
# yum module enable __module-name__:__previous-stream__
----
====

. For every other module stream that was enabled as a dependency in the first step, return the module to the previous state, too.

ifdef::appstream-book[]

.Additional resources

* xref:commands-for-listing-content_finding-rhel-8-content[]

endif::[]
