[id="commands-for-installing-rhel-8-content_{context}"]
= Commands for installing {rel8} content

This section lists commonly used commands for installing {rel8} content.

.Command list


Install a package::
+
[subs="quotes"]
----
# yum install _package_
----
+
If the package is provided by a module stream, [command]`yum` resolves the required module stream, and enables it automatically while installing this package. This happens recursively for all package dependencies, too. If more module streams satisfy the requirement, the default ones are used.


Enable a module using its default stream::
+
[subs="quotes"]
----
# yum module enable __module-name__
----
+
Enable the module when you wish to make the packages available to the system but do not, at this time, wish to install any of them.
//In prior versions of {ProductName}, this would be equivalent to adding a new yum repository but not actually installing any packages from it.
+
Some modules may not define default streams. In such case, you must explicitly specify the stream.


Enable a module using a specific stream::
+
[subs="quotes"]
----
# yum module enable __module-name__:__stream__
----
+
If the module defines a default stream, you can omit the stream and colon.


Install a module using the default stream and profiles::
+
[subs="quotes"]
----
# yum install @__module-name__
----
+
Alternatively:
+
[subs="quotes"]
----
# yum module install __module-name__
----
+
CAUTION: Some modules do not define default streams.


Install a module using a specific stream and default profiles::
+
[subs="quotes"]
----
# yum install @__module-name__:__stream__
----
+
Alternatively:
+
[subs="quotes"]
----
# yum module install __module-name__:__stream__
----
+
// CAUTION: It is theoretically possible that different streams might specify differently named profiles as default. This is not in Alpha, however.


Install a module using a specific stream and profile::
+
[subs="quotes"]
----
# yum install @__module-name__:__stream__/__profile__
----
+
Alternatively:
+
[subs="quotes"]
----
# yum module install __module-name__:__stream__/__profile__
----
+
// NOTE: This is the only fully defined/qualified variant of installation. Prefer this invocation in automation.
