include::ROOT:partial$attributes.adoc[]
include::partial$local-attributes.adoc[]
[id="installation-workflow_{context}"]
= Installation workflow

This installation workflow contains the high-level steps for installing {productname} on AMD64, Intel 64, and 64-bit ARM architectures using the graphical user interface.

.Procedure

. Prepare for your installation by checking your system and hardware requirements, downloading an installation image file, and creating bootable installation media.
. Boot the installation program and install {productname} using the graphical user interface.
. Complete post-installation tasks such as initial setup and system registration.

ifdef::installation-title[]

.Additional resources

* For more information about preparing for your installation, see <<preparing-for-your-installation_installing-RHEL>>.
* For more information about booting the installation program, see <<booting-the-installer_installing-RHEL>>.
* For more information about installing {productname} using the graphical user interface, see <<graphical-installation_graphical-installation>>
* For more information about completing post-installation tasks, see <<post-installation-tasks_installing-RHEL>>.

endif::[]
